### ISSUE TITLE
Can't get the form to work

### ISSUE THREAD

**Issue by epstrada** [aerohub/hugo-identity-theme#20]
Hi,

I have the form set up and functional. However, the confirmation message is not displayed on succes.

**Comment by stp-ip** [comment]
Can you try with the latest changes. A lot of improvements concerning the form went into the latest iteration.

**Comment by loganblevins** [comment]
Form still isn't working. I registered my domain and got my site key for Invisible ReCaptcha. However, the ReCaptcha isn't invisible. Once I visibly verify to send, nothing happens. The response is a Formspree HTML page, rather than what this code expects.

**Comment by stp-ip** [comment]
Will try to test and fix any issues with formspree and the latest changes to the form. If you have some more details, that would be appreciated.

**Comment by loganblevins** [comment]
Sure. Thank you for the quick reply. It appears that Formspree issues a redirect to their webpage, which then has its own ReCaptcha that needs to be verified. 

If we try to get around this by implementing our own Inivisible ReCaptcha on the webpage with the actual form, the webpage will not issue a redirect to the Formspree verification page like It would otherwise. The Hugo theme gets the token for verification just fine if we implement Invisible ReCaptcha, but when we check the response for code 200, the code is null which breaks everything. The response handed back to us is actually an HTML page containing the redirect request to Formspree, since Formspree wants to force your form to redirecting and verifying on the Formspree end independently.

My form finally works now, but I had to remove all traces of the Hugo custom Invisible ReCaptcha. Now, Formspree is redirecting to its page and verifying for us. This is very ugly and unfriendly but it works. Apparently to disable Formspree ReCaptcha, we need to upgrade to their paid account level. This is unfortunate. Can this fixed?

**Comment by stp-ip** [comment]
Probably easiest thing is to add a switch to only use the captcha, when a non formspree config is used.

If you dislike the formspree redirect you can take a look at using gmail/or another smtp capable provider and something like: https://caddyserver.com/docs/http.mailout

**Comment by epstrada** [comment]
thx! will test again
